import { Router } from 'express';
import { z } from 'zod';

import type {
  SecurityLesson,
  SecurityModule as SecurityModuleModel,
  VibeChallenge,
  SecurityProgress,
  SecurityPreference,
} from '@prisma/client';

import type { AuthedRequest } from '../middleware/jwt-middleware.js';
import { requireAuth } from '../middleware/jwt-middleware.js';
import { prisma } from '../prisma.js';

const router = Router();

const formatModule = (
  module: SecurityModuleModel & { lessons: SecurityLesson[]; challenges: VibeChallenge[] },
  progress?: SecurityProgress | null,
) => {
  const topics = JSON.parse(module.topics || '[]') as string[];
  const lessons = module.lessons.sort((a, b) => a.sortOrder - b.sortOrder);
  const challenges = module.challenges.map((challenge) => ({
    ...challenge,
    hints: JSON.parse(challenge.hints || '[]'),
    heuristics: JSON.parse(challenge.heuristics || '[]'),
  }));
  const parsedProgress = progress
    ? {
        id: progress.id,
        moduleId: progress.moduleId,
        completedLessons: JSON.parse(progress.completedLessons || '[]') as string[],
        completedChallenges: JSON.parse(progress.completedChallenges || '[]') as string[],
        vibeConfidence: progress.vibeConfidence,
        notes: progress.notes,
        updatedAt: progress.updatedAt,
      }
    : null;

  return {
    ...module,
    topics,
    lessons,
    challenges,
    progress: parsedProgress,
  };
};

const analyzeSchema = z.object({
  code: z.string().min(20),
  url: z.string().url().optional(),
});

const analyzeSnippet = (code: string) => {
  const lines = code.split(/\r?\n/).filter((line) => line.trim().length > 0);
  const lineCount = lines.length;
  const avgLineLength = lines.reduce((sum, line) => sum + line.length, 0) / Math.max(lineCount, 1);
  const commentLines = lines.filter((line) => /\/\/|\/\*|<!--|-->/i.test(line)).length;
  const commentDensity = lineCount > 0 ? commentLines / lineCount : 0;
  const hasTodo = /TODO|FIXME|later lol/i.test(code);
  const hasExternalPaste = /(pastebin|gist\.githubusercontent|raw\.github)/i.test(code);
  const hasUniformClassPattern = /class(Name)?="[\w-]+(Container|Wrapper|Card|Title)"/g.test(code);
  const hasGenericCopy = /(start journey|best fits your success story|unlock potential)/i.test(code);
  const hasInlineStyle = /style\s*=\s*["']/.test(code);
  const minifiedLikely = /\)\}\);?$/.test(lines[lines.length - 1] ?? '') && lines.every((l) => !l.includes('  '));

  const signalScore =
    (hasExternalPaste ? 0.25 : 0) +
    (hasTodo ? 0.1 : 0) +
    (hasUniformClassPattern ? 0.15 : 0) +
    (hasGenericCopy ? 0.15 : 0) +
    (hasInlineStyle ? 0.1 : 0) +
    (minifiedLikely ? 0.15 : 0) +
    (commentDensity < 0.02 ? 0.1 : 0);

  const verdict =
    signalScore > 0.7
      ? 'Likely AI-generated or hastily stitched together'
      : signalScore > 0.4
        ? 'Mixed signals — review with a human teammate'
        : 'Feels handcrafted or at least reviewed by a human';

  const highlights = [
    hasExternalPaste && 'External script references (paste services) raise supply-chain questions.',
    hasUniformClassPattern && 'Uniform class naming pattern mirrors common boilerplate exports.',
    hasGenericCopy && 'Marketing copy reads like template filler.',
    hasInlineStyle && 'Inline styling on primary actions usually indicates rushed implementation.',
    minifiedLikely && 'Minified JSX suggests autogenerated output.',
    commentDensity < 0.02 && 'Scarce comments or rationale recorded in code.',
  ].filter(Boolean);

  return {
    score: Number(signalScore.toFixed(2)),
    verdict,
    metrics: {
      lineCount,
      avgLineLength: Number(avgLineLength.toFixed(1)),
      commentDensity: Number(commentDensity.toFixed(2)),
    },
    signals: highlights,
  };
};

router.get('/modules', async (_req, res, next) => {
  const req = _req as AuthedRequest;
  try {
    const modules = await prisma.securityModule.findMany({
      include: { lessons: true, challenges: true },
      orderBy: { createdAt: 'asc' },
    });
    let progressMap: Record<string, SecurityProgress> = {};
    if (req.user) {
      const progress = await prisma.securityProgress.findMany({
        where: { userId: req.user.id },
      });
      progressMap = progress.reduce<Record<string, SecurityProgress>>((acc, record) => {
        acc[record.moduleId] = record;
        return acc;
      }, {});
    }
    res.json({
      modules: modules.map((module) => formatModule(module, progressMap[module.id])),
    });
  } catch (error) {
    next(error);
  }
});

router.get('/modules/:id', async (req, res, next) => {
  try {
    const module = await prisma.securityModule.findUnique({
      where: { id: req.params.id },
      include: { lessons: true, challenges: true },
    });
    if (!module) {
      return res.status(404).json({ message: 'Module not found' });
    }
    let progress: SecurityProgress | null = null;
    if ((req as AuthedRequest).user) {
      progress = await prisma.securityProgress.findUnique({
        where: {
          moduleId_userId: {
            moduleId: module.id,
            userId: (req as AuthedRequest).user!.id,
          },
        },
      });
    }
    res.json({ module: formatModule(module, progress ?? undefined) });
  } catch (error) {
    next(error);
  }
});

router.get('/challenges', async (_req, res, next) => {
  try {
    const challenges = await prisma.vibeChallenge.findMany({
      include: {
        module: true,
      },
      orderBy: { createdAt: 'desc' },
    });
    res.json({
      challenges: challenges.map((challenge) => ({
        ...challenge,
        hints: JSON.parse(challenge.hints || '[]'),
        heuristics: JSON.parse(challenge.heuristics || '[]'),
        module: challenge.module ? formatModule({ ...challenge.module, lessons: [], challenges: [] }) : null,
      })),
    });
  } catch (error) {
    next(error);
  }
});

router.post('/analyze-code', async (req, res, next) => {
  try {
    const { code, url } = analyzeSchema.parse(req.body);
    const analysis = analyzeSnippet(code);
    res.json({
      analysis,
      metadata: {
        url,
        timestamp: new Date().toISOString(),
      },
    });
  } catch (error) {
    next(error);
  }
});

router.get('/progress', requireAuth, async (req: AuthedRequest, res, next) => {
  try {
    const records = await prisma.securityProgress.findMany({
      where: { userId: req.user!.id },
    });
    res.json({
      progress: records.map((record) => ({
        ...record,
        completedLessons: JSON.parse(record.completedLessons || '[]'),
        completedChallenges: JSON.parse(record.completedChallenges || '[]'),
      })),
    });
  } catch (error) {
    next(error);
  }
});

router.post('/progress', requireAuth, async (req: AuthedRequest, res, next) => {
  try {
    const schema = z.object({
      moduleId: z.string(),
      completedLessons: z.array(z.string()).optional(),
      completedChallenges: z.array(z.string()).optional(),
      vibeConfidence: z.number().min(0).max(1).optional(),
      notes: z.string().max(500).optional(),
    });
    const data = schema.parse(req.body);
    const progress = await prisma.securityProgress.upsert({
      where: {
        moduleId_userId: {
          moduleId: data.moduleId,
          userId: req.user!.id,
        },
      },
      update: {
        completedLessons: data.completedLessons ? JSON.stringify(data.completedLessons) : undefined,
        completedChallenges: data.completedChallenges ? JSON.stringify(data.completedChallenges) : undefined,
        vibeConfidence: data.vibeConfidence ?? undefined,
        notes: data.notes ?? undefined,
      },
      create: {
        moduleId: data.moduleId,
        userId: req.user!.id,
        completedLessons: JSON.stringify(data.completedLessons ?? []),
        completedChallenges: JSON.stringify(data.completedChallenges ?? []),
        vibeConfidence: data.vibeConfidence ?? 0,
        notes: data.notes ?? '',
      },
    });
    res.status(201).json({
      progress: {
        ...progress,
        completedLessons: JSON.parse(progress.completedLessons || '[]'),
        completedChallenges: JSON.parse(progress.completedChallenges || '[]'),
      },
    });
  } catch (error) {
    next(error);
  }
});

router.get('/preferences', requireAuth, async (req: AuthedRequest, res, next) => {
  try {
    const preferences = await prisma.securityPreference.findUnique({
      where: { userId: req.user!.id },
    });
    res.json({
      preferences: preferences
        ? {
            ...preferences,
            shortcuts: JSON.parse(preferences.shortcuts || '[]'),
          }
        : null,
    });
  } catch (error) {
    next(error);
  }
});

router.post('/preferences', requireAuth, async (req: AuthedRequest, res, next) => {
  try {
    const schema = z.object({
      onboardingComplete: z.boolean().optional(),
      preferredTone: z.enum(['security', 'ai', 'wellness', 'finance', 'education']).optional(),
      shortcuts: z.array(z.string()).max(6).optional(),
    });
    const data = schema.parse(req.body);
    const preferences = await prisma.securityPreference.upsert({
      where: { userId: req.user!.id },
      update: {
        onboardingComplete: data.onboardingComplete ?? undefined,
        preferredTone: data.preferredTone ?? undefined,
        shortcuts: data.shortcuts ? JSON.stringify(data.shortcuts) : undefined,
      },
      create: {
        userId: req.user!.id,
        onboardingComplete: data.onboardingComplete ?? false,
        preferredTone: data.preferredTone ?? 'security',
        shortcuts: JSON.stringify(data.shortcuts ?? []),
      },
    });

    res.status(201).json({
      preferences: {
        ...preferences,
        shortcuts: JSON.parse(preferences.shortcuts || '[]'),
      },
    });
  } catch (error) {
    next(error);
  }
});

router.get('/incidents', requireAuth, async (req: AuthedRequest, res, next) => {
  try {
    const incidents = await prisma.securityIncident.findMany({
      where: { ownerId: req.user!.id },
      orderBy: { detectedAt: 'desc' },
      include: { tasks: true },
    });
    res.json({ incidents });
  } catch (error) {
    next(error);
  }
});

const incidentSchema = z.object({
  title: z.string().min(3),
  severity: z.enum(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']),
  description: z.string().min(10),
  source: z.string().min(2),
  detectedAt: z.string().datetime(),
});

router.post('/incidents', requireAuth, async (req: AuthedRequest, res, next) => {
  try {
    const data = incidentSchema.parse(req.body);
    const incident = await prisma.securityIncident.create({
      data: {
        ...data,
        ownerId: req.user!.id,
      },
    });
    res.status(201).json({ incident });
  } catch (error) {
    next(error);
  }
});

router.patch(
  '/incidents/:id/status',
  requireAuth,
  async (req: AuthedRequest, res, next) => {
    try {
      const schema = z.object({
        status: z.enum(['OPEN', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED']),
      });
      const { status } = schema.parse(req.body);
      const incident = await prisma.securityIncident.update({
        where: { id: req.params.id, ownerId: req.user!.id },
        data: {
          status,
          resolvedAt: status === 'RESOLVED' ? new Date() : undefined,
        },
      });
      res.json({ incident });
    } catch (error) {
      next(error);
    }
  },
);

const taskSchema = z.object({
  title: z.string().min(3),
  details: z.string().min(5),
  dueAt: z.string().datetime().optional(),
  incidentId: z.string().optional(),
});

router.post('/tasks', requireAuth, async (req: AuthedRequest, res, next) => {
  try {
    const data = taskSchema.parse(req.body);
    const task = await prisma.securityTask.create({
      data: {
        title: data.title,
        details: data.details,
        dueAt: data.dueAt ? new Date(data.dueAt) : undefined,
        ownerId: req.user!.id,
        incidentId: data.incidentId,
      },
    });
    res.status(201).json({ task });
  } catch (error) {
    next(error);
  }
});

router.patch('/tasks/:id', requireAuth, async (req: AuthedRequest, res, next) => {
  try {
    const schema = z.object({
      status: z.enum(['PENDING', 'ACTIVE', 'DONE']).optional(),
      dueAt: z.string().datetime().optional(),
      checklistUrl: z.string().url().optional(),
    });
    const data = schema.parse(req.body);
    const task = await prisma.securityTask.update({
      where: { id: req.params.id, ownerId: req.user!.id },
      data: {
        status: data.status,
        dueAt: data.dueAt ? new Date(data.dueAt) : undefined,
        checklistUrl: data.checklistUrl,
      },
    });
    res.json({ task });
  } catch (error) {
    next(error);
  }
});

export { router as securityRouter };

